# Generated by Django 3.2.18 on 2023-04-15 16:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefinancas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('ESCOLHA', 'Escolha uma categoria'), ('CSA', 'Casa'), ('EDU', 'Educação'), ('ETR', 'Eletrônicos'), ('LZR', 'Lazer'), ('SD', 'Saúde'), ('SPR', 'Supermercado'), ('TRS', 'Transoorte'), ('OTR', 'Outros')], default='ESCOLHA', max_length=10),
        ),
        migrations.AlterField(
            model_name='receita',
            name='categoria',
            field=models.CharField(choices=[('ESCOLHA', 'Escolha uma categoria'), ('PRS', 'Presente'), ('PRM', 'Prêmio'), ('SLR', 'Salário'), ('OTS', 'Outros')], default='ESCOLHA', max_length=10),
        ),
    ]
