# Generated by Django 3.2.18 on 2023-04-15 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('controlefinancas', '0002_auto_20230415_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='despesa',
            name='categoria',
            field=models.CharField(choices=[('ESCOLHA', 'Escolha uma categoria'), ('CSA', 'Casa'), ('EDU', 'Educação'), ('ETR', 'Eletrônicos'), ('LZR', 'Lazer'), ('SD', 'Saúde'), ('SPR', 'Supermercado'), ('TRS', 'Transporte'), ('OTR', 'Outros')], default='ESCOLHA', max_length=10),
        ),
    ]
